version: '3'
services:
  redis:
    image: redis:4.0.6-alpine
    restart: always
    ports:
      - "6379:6379"
  mongo:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  executor:
    build: ./Executor
    image: rmni/executor:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - ./Executor:/Executor
    depends_on:
      - redis
  server:
    build: ./Server
    image: rmni/server:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    network_mode: "host"
    depends_on:
      - redis
    volumes:
      - ./Server:/Server
  socketio:
    build: ./SocketIO
    image: rmni/socketio:latest
    restart: unless-stopped
    ports:
      - '7000:7000'
    network_mode: "host"
    volumes:
      - ./SocketIO:/SocketIO
