services:
  redis:
    image: redis:4.0.6-alpine
    restart: always
    ports:
      - "6379:6379"
  mongo:
    image: mongo:6.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminuser
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  executor:
    build: ./services/executor
    restart: unless-stopped
    # ports:
    #   - "5001:5001"
    volumes:
      - ./storage:/Executor/storage
    depends_on:
      - redis
  server:
    build: ./services/server
    restart: unless-stopped
    # ports:
    #   - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./storage:/Server/storage
  socketio:
    build: ./services/socketIO
    restart: unless-stopped
    ports:
      - '7000:7000'
    # network_mode: "host"
  webapp:
    build: ./services/webapp
    restart: unless-stopped
  nginx:
    build: ./services/nginx
    restart: unless-stopped
    ports:
      - 80:80
volumes:
  storage:
