version: '3'
services:
  redis:
    image: redis:4.0.6-alpine
    # ports:
    #   - "6379:6379"
  executor:
    build: ./Executor
    image: legraina/executor:latest
    # ports:
    #   - "5001:5001"
    volumes:
      - ./Executor:/Executor
    depends_on:
      - redis
  server:
    build: ./Server
    image: legraina/server:latest
    # ports:
    #   - "5000:5000"
    # network_mode: "host"
    depends_on:
      - redis
    volumes:
      - ./Server:/Server
  socketio:
    build: ./SocketIO
    image: legraina/socketio:latest
    # ports:
    #   - '7000:7000'
    # network_mode: "host"
    volumes:
      - ./SocketIO:/SocketIO
