apiVersion: v1
kind: Secret
metadata:
  name: redis-consumer
data:
  RedisHost: bG9jYWxob3N0
  RedisPort: NjM3OQ==
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: job-executor
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
        - name: scapist-executor
          image: scapist/executor
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: "10240Mi"
        restartPolicy: Never
    backoffLimit: 0  
  pollingInterval: 1
  maxReplicaCount: 1
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  scalingStrategy:
    strategy: "default"
  triggers:
  - type: redis
    metadata:
      address: redis.default:6379
      listName: job_queue
      listLength  : '1'
