apiVersion: v1
kind: Secret
metadata:
  name: redis-consumer
data:
  RedisHost: bG9jYWxob3N0
  RedisPort: NjM3OQ==
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: job-executor
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        volumes:
          - name: nfs-storage
            nfs:
              server: 10.105.99.184  # ip of the nfs service
              path: /
              readOnly: no
        containers:
          - name: executor
            image: rmni/executor:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 5000
                protocol: TCP
            resources:
              limits:
                memory: 5G
            volumeMounts:
              - mountPath: /mnt/storage
                name: nfs-storage
            env:
              - name: STORAGE
                value: /mnt/storage
              - name: MAX_RETRY
                value: "5"
              - name: MAX_RAM_GB
                value: "5"
            terminationMessagePolicy: FallbackToLogsOnError
        restartPolicy: Never
    backoffLimit: 5
    activeDeadlineSeconds: 14000  #  Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
  pollingInterval: 1
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  scalingStrategy:
    strategy: "default"
  triggers:
  - type: redis
    metadata:
      address: redis.default:6379
      listName: job_queue
      listLength: '1'
