---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: mongo-server
  selector:
    app: mongo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    pv: mongo
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kubadm/k8s-storage/mongodb"
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2G
  selector:
    matchLabels:
      pv: mongo
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: adminuser
          image: mongo:4.4.18
          name: mongo
          ports:
            - name: mongo-server
              containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-pv
      restartPolicy: Always
      volumes:
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pvc
