---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: mongo-server
  selector:
    app: mongo
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: adminuser
          image: mongo:6.0
          name: mongo
          ports:
            - name: mongo-server
              containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-vol
      restartPolicy: Always
      volumes:
        - name: mongo-vol
          hostPath:
            path: /data/mongo
            type: Directory
