---
apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  ports:
    - port: 2049
      targetPort: 2049-tcp
      protocol: TCP
  type: NodePort
  selector:
    app: nfs
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nfs
  name: nfs
spec:
  replicas: 1
  selector:
    app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - image: itsthenetwork/nfs-server-alpine
          name: nfs
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - name: 2049-tcp
              containerPort: 2049
          volumeMounts:
            - mountPath: /mnt/nfs_share
              name: nfs-vol
              mountPropagation: Bidirectional
          env:
            - name: SHARED_DIRECTORY
              value: /mnt/nfs_share
      restartPolicy: Always
      volumes:
        - name: nfs-vol
          hostPath:
            path: /data/nfs  # for minikube: see https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
            type: Directory
