---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
      - port: 6379
        targetPort: redis-server
  selector:
    app: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
        labels:
            app: redis
    spec:
        containers:
            - image: redis:4.0.6-alpine
              name: redis
              ports:
                - name: redis-server
                  containerPort: 6379
        restartPolicy: Always
