name: Publish All Docker images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_executor_to_dockerhub:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image: rmni/executor
      context: ./services/executor
    secrets: inherit

  push_server_to_dockerhub:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image: rmni/server
      context: ./services/server
    secrets: inherit

  push_webapp_to_dockerhub:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image: rmni/webapp
      context: ./services/webapp
    secrets: inherit

  push_socketio_to_dockerhub:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image: rmni/socketio
      context: ./services/socketIO
    secrets: inherit
